<?php

 /**
 * @file
 * Remove shortlink
 *
 * @section LICENSE
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @details    Showing metatags in nodes
 * @category   PARQUES_REUNIDOS
 * @version    $Id: metatag_short_seo.module 0 2013-06-25
 * @author     Pedro Iturriaga <pedro.iturriaga@ipit.biz>
 * @file       /sites/all/modules/custom/metatag_short_seo/metatag_short_seo.module
 * @copyright  GNU Public License
 * @link       http://www.gnu.org/licenses/gpl.html
 */

/**
 * Implements hook_html_head_alter
 */
function metatag_short_seo_html_head_alter(&$head_elements) {

	// Remove shortlink link
	if (isset($head_elements['metatag_shortlink'])) {
    unset($head_elements['metatag_shortlink']);
	}
}
